project:
  type: website
  output-dir: _site

website:
  title: "Rafael Condé Gomes"
  site-url: "https://condeg0.github.io/RafaelCondeGomes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About

execute:
  freeze: auto
