project:
  type: website
  output-dir: _site
  resources:
    - lang-toggle.js

website:
  title: "Rafael Condé Gomes"
  site-url: "https://condeg0.github.io/RafaelCondeGomes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
  page-footer:
    left: "© Rafael Condé Gomes"
    right:
      - icon: envelope
        href: mailto:condeg.rafael@gmail.com
      - icon: linkedin
        href: https://www.linkedin.com/in/rafael-conde-878284250/
      - icon: github
        href: https://github.com/Condeg0

format:
  html:
    css: lang-toggle.css
    include-after-body: lang-toggle.html

execute:
  freeze: auto
